### ISSUE TITLE
Initialization during inference

### ISSUE THREAD

**Issue by MaxEAB** [hkchengrex/XMem#72]
Hi, Is it possible to initialize tracking using a mask and frame (or a sequence of frames) that is saved in advance? This is for single object tracking when the object to be tracked is known in advance.

**Comment by MaxEAB** [comment]
Hi, Thanks for the reply. I meant a scenario in which the initial reference frame is known/saved in advance, but the tracking will happen live using the saved reference images. Is this possible with this flavor of XMem? 

Basically, the user will not actively initiate the process.

**Comment by hkchengrex** [comment]
I am not sure if I understand. Where do the images to be segmented come from? What do you mean by live?

**Comment by hkchengrex** [comment]
If the user is not initiating... who is?

**Comment by hkchengrex** [comment]
I see. Thank you for the explanation.
In that case, I would still treat the input as a "video", except that the first frame is quite different than the second. I would also reset the sensory memory at the second frame due to this difference. For multiple objects, we can save all of them to the working memory (and force them to remain in the working memory at all times). Some inference logic would have to be rewritten.
Whether it would work well depends largely on how different the reference and the query are.
